### ISSUE TITLE
Google login redirects to wrong domain

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/webapp#633] opened 2018-01-29 21:45 UTC
> The login didn't work fine for me in Google Chrome and while loggin in into the gmail account there was a message, that after login I will be redirected to the test.elimu.ai, so I just tried this address.

**Comment by JakubRuzicka** [comment] 2018-10-05 12:57
I can't reproduce this bug. Can you write more details how to reproduce it please?

**Comment by nya-elimuai** [comment] 2020-12-21 12:45
Was fixed in #699

**Closed by nya-elimuai** 2020-12-21 12:45 UTC
Labels: bug
